site_name: catena
theme:
  name: material
  custom_dir: docs/overrides
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
nav:
  - Home: index.md
  - Examples: 
      - Quick examples: examples.md
      - Short projects: projects.md
  - API Reference:
      - catena: api/catena.md
      - generators: api/generators.md
      - views: api/views.md
      - cache: api/cache.md
      - mathlib: api/mathlib.md
      - strings: api/strings.md
  - Theory:
      - catena: theory/theory.md
      - catena.mathlib.convert.from_quadratic_surd_to_scf: theory/from_quadratic_surd_to_scf.md