[build-system]
requires = ["hatchling>=1.29.0"]
build-backend = "hatchling.build"

[project]
name = "catena-scf"
version = "0.6.0"
authors = [
  { name = "Lorenzo Silva Moore", email = "lorenzosilvamoore@ciencias.unam.mx" },
]
description = "A Python library for simple continued fractions"
readme = {file = "README.md", content-type = "text/markdown"}
requires-python = ">=3.12"
dependencies = []
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "GPL-3.0-or-later"
license-files = ["LICEN[CS]E*"]

[project.urls]
Repository = "https://github.com/LorenzoSilvaMoore/catena"
Issues = "https://github.com/LorenzoSilvaMoore/catena/issues"
Documentation = "https://lorenzosilvamoore.github.io/catena/"

[tool.hatch.build.targets.wheel]
packages = ["catena"]

[tool.hatch.build.targets.sdist]
exclude = ["docs/", "testing/"]

[tool.pytest.ini_options]
testpaths = ["testing"]
